### ISSUE TITLE
Naming runcards/results directories

### ISSUE THREAD

**Issue by c-j-johnston** [wilsonmr/anvil#17]
Just a thought on some naming conventions and the command line input -- perhaps it would be best if the output directory with checkpoints/plots is given the same name as the runcard by default so that we can track things more easily. Don't want to change this without checking though!

**Comment by wilsonmr** [comment]
So I've been thinking a bit about this and I think there are a couple of related bits some of which should probably be accounted for in #16 

There are two completely seperate tasks which I actually believe should have different command line scripts (because they're so distinct): training and sampling

Now training needs to output something which contains enough information that we can easily do the sampling/observables on it. I think we should define a `TrainedModel` which is an output folder which is uniquely named (I'll come to this) the output folder contains the runcard which generated it, training logs, and saved checkpoints. The easiest way to name the fits is probably date (in reverse order so 9th November 2019 is 191109 followed by the initials of person who ran it (for me mw) followed by a 3 digit number which represents how many fits of that kind I have ran today, possibly followed by the lattice length just for quick identification. So today the first training I'd do would be called 191109-mw-001-6, we should call the runcard `191109-mw-001-6` and by default the training output will be named the same, however there could be a `-o <different output name>`   in case people wanted to specify something different at runtime. I  think with this system there is no chance of us double naming things. We need to make it easy to retrain something, maybe the train script could either take a runcard.yml or take a `--retrain <output folder>`

The sampling output is less important - in my opinion. Because it takes less time and because we might want to sample several different models at once and compare or something

In #16 I used inspiration from other projects I've worked on where the structure is very nice - especially for science related things.. Actually they use something one of my collaborators developed called [reportengine](https://github.com/NNPDF/reportengine/) I am very on the fence whether we should just use this, because it will make generating plots and looping over things way easier, because it has lots of tools for that. The downside is it has some kind of high level concepts and I don't want people getting bogged down with that instead of focusing on the project. If we were to use it, then it provides a standard for analysis output folders which I personally would just follow. I'll let you know what I decide

**Comment by c-j-johnston** [comment]
That all sounds good. One thing which could be useful to add in the command line for sampling is the checkpoint to sample from, becuase right now I've been creating new (but very similar) runcards for each CP I want to sample from.

**Comment by wilsonmr** [comment]
Hmm I think there could be easier ways to do the checkpoint but I'd rather keep it declaritive (and copy runcards into output also with sampling) so that we have a record of exactly what was sampled... I can see it's a pain though if you just want to sample a few different checkpoints

I think in the end we will probably want to be able to either loop over checkpoints or loop over different trained models taking just the final checkpoint - this indeed is something which reportengine would be incredibly good for

**Comment by wilsonmr** [comment]
I think this essentially is implemented in #20 it's up to individuals what naming convention they take, but the model names must be unique
