### ISSUE TITLE
states should be like (n_batch, n_field_dim, n_lattice)

### ISSUE THREAD

**Issue by wilsonmr** [wilsonmr/anvil#41]
this would involve changing some of the distributions, models and targets but I think it would make it a bit more clear, at least to me, the layout of the states

probbaly isn't so much work and if its just me that wants it then perhaps its not worth it

I *think* the nvp can handle it now, so it would just be about changing the ProjectSphere

**Comment by jmarshrossney** [comment]
I'm not sure this does what we want though, because the extra dimension will be treated as another batch dimension, so all angles at a given lattice site will be transformed under the same mapping.

From [PyTorch documentation for Linear layers](https://pytorch.org/docs/stable/nn.html#linear-layers):
*Input: (N, ∗, H_in) where ∗ means any number of additional dimensions and H_in = in_features*

So if we do what we're doing now:
```
def forward(self, x_input) -> torch.Tensor:
    x_a = x_input[..., self._a_ind]
    x_b = x_input[..., self._b_ind]
    x_a_stand = self.standardise(x_a)
    s_out = self.s_network(x_a_stand)
    t_out = self.t_network(x_a_stand)
...
```
we will get the right shape output but the neural networks will not treat the extra dimensions as additional 'features'. Quite frustrating because it would be much cleaner if this worked.

**Comment by wilsonmr** [comment]
yeah you're right. Not only would the angles be transformed under the same mapping, they also would be completely decoupled. I definitely didn't think about this when I had the idea
