### ISSUE TITLE
Structuring of the project

### ISSUE THREAD

**Issue by jmarshrossney** [wilsonmr/anvil#8]
The "observables" branch is partly a vague attempt to modularize things, while looking ahead to when we might be wanting to use different models, and maybe go to d>2 etc.

This is just one possible way of structuring the project and one which we don't have to adopt.

Alternative suggestions could be put forward and discussed on this issue thread.

**Comment by wilsonmr** [comment]
this is a nice start but there are some things I think I would change, I think at some point it would be best to just adopt the standard structure of python modules (see for example https://github.com/matplotlib/matplotlib). Obviously our project is much smaller but a multi-directory style would work a lot better

Also there are the observables which are kind of a seperate issue although I can see that having a nicer structure probably makes implementing the observables easier

I think the best approach moving forward is to open a PR for the branch where we will mainly be looking at closing #9 and having the observables implemented and working. If that requires a bit of restructuring then fair enough

I think there should be a seperate PR which restructures the code because otherwise there is a lot to review and to quite orthogonal issues (one is whether the observables are correct and the other is whether the code is structured in a better way)

Also side note and sorry to be critical but I think useful commit messages would be better than meaningless version IDs If we want to make version tags there are proper ways to do this. I'd rather see 'I added a rough first attempt at observables' and 'fixing issue with pole mass giving something balalabla' for obvious reasons when scanning back through commits

**Comment by jmarshrossney** [comment]
Ok, cheers, that seems sensible.

I can easily shoehorn the observables code back into the existing structure and then open a pull request, if that makes it easier for everyone to work with.

And yeah, point taken re commit messages.
